FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json* ./

RUN npm ci

COPY . .

EXPOSE 2025

ENV PORT=2025
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "run", "dev"]
